package net.parttimepolymath.sandbox.springboot.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.util.UUID;

/**
 * another simple POJO to represent the outgoing response from our service.
 *
 * @since 2020-06027
 * @author Robert Hook
 */
@Builder
@ToString
@EqualsAndHashCode
@Data
@AllArgsConstructor
public class EchoResponse {
    /**
     * a message ID generated by our service
     */
    @JsonProperty
    private UUID id;

    /**
     * the message we are sending back.
     */
    @JsonProperty
    private String message;

    /**
     * we need a specific alternate constructor so that we can convert a JSON string back to a response object
     * in our tests.
     * @param id the string, which is assumed to be convertible to an UUID.
     * @param message the message to include, which may be null.
     */
    @JsonCreator
    public EchoResponse(@JsonProperty("id") final String id, @JsonProperty("message") final String message) {
        this.id = UUID.fromString(id);
        this.message= message;
    }
}
