package net.parttimepolymath.sandbox.springboot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.UUID;

/**
 * another simple POJO to represent the outgoing response from our service.
 *
 * Note that we are a little more constrained than on the request object, and only allow construction and JSON
 * serialisation.
 *
 * @since 2020-06027
 * @author Robert Hook
 */
@Builder
@ToString
@EqualsAndHashCode
public class EchoResponse {
    /**
     * a message ID generated by our service
     */
    @JsonProperty
    private UUID id;

    /**
     * the message we are sending back.
     */
    @JsonProperty
    private String message;
}
